config/routes.rb
Rails.application.routes.draw do
  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  devise_for :users
  root to: "home#index"
  resources :files, only: [:new, :create]
  resources :uploads
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :userfile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
    def new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
  end

  def create
    Rails.logger.debug current_user.userfile
    @current_user.userfile.purge
    @current_user.userfile.attach(params[:userfile])
    redirect_to action: 'index'
  end

  def index
    Rails.logger.debug current_user.userfile
    if current_user.userfile.attached?
      @userfile = url_for(@current_user.userfile)
    else
      @userfile = ""
    end
    Rails.logger.debug @userfile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  private
    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/files/new.html.erb
<h1>Files</h1>

<p>Submit a file to upload to upload to amazon s3 services.</p>

<form action="http://localhost:3000/api/v1/items"
      enctype="multipart/form-data"
      method="post"
      class="form-signin">
<p>
What file are you sending? <input type="file" class="" name="file"><br>
</p>
<input type="submit" value="Upload" class="btn btn-lg btn-primary btn-block mt-4">
</form>

app/views/home/index.html.erb
<h1>Homepage </h1>
<p>This website is for testing AWS S3 uploads. <a href="/uploads/new">Upload New File</a></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "alert alert-success" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active"><%= link_to 'Home', root_path, class: "nav-link" %></li>
    <%= render 'layouts/navigation_links' %>
  </ul>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

    <li class="nav-item active"><a href="/uploads" class="nav-link">User File/Upload</a></li>
      <% if user_signed_in? %>
        <li class="nav-item active"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %></li>
        <li class="nav-item active"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %></li>
        <li class="nav-item active text-light pt-2 pl-4">Logged in as <strong><%= current_user.email %></strong>.</li>
      <% else %>
        <li class="nav-item active"><%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %></li>
        <li class="nav-item active"><%= link_to "Login", new_user_session_path, :class => 'nav-link'  %></li>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Swayuploader" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Swayuploader" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container-fluid flex">
      <div class="row">
        <div class="col-2 col-md-2"></div>
        <div class="col-8 col-md-8 bg-light border-dark p-5 m-4 border">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
        <div class="col-2 col-md-2"></div>
      </div>
    </main>
  </body>
</html>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/index.html.erb
<h1>All uploads</h1>
<div>
	<% if @userfile != '' %>
		<p><a target="_blank" href="<%= @userfile %>">User Uploaded File</a></p>
	<% else %>
		<p>A file has not been uploade for the user yet.</p>
	<% end %>
	<p><a href="/uploads/new">Upload New File</a></p>
</div>

app/views/uploads/new.html.erb
<h1>Upload a file</h1>

<%= form_tag uploads_path, enctype: 'multipart/form-data' do %>
	<%= file_field_tag :userfile  %>
	<%= submit_tag 'Upload file' %>
<% end %>